### ISSUE TITLE
Badges

### ISSUE THREAD

**Issue by moul** [SIGSEV/Starveller#23]
would be a killer feature !

**Comment by balthazar** [comment]
Yeah indeed, thanks for the idea!

Would you see a simple shield.io or something more like the Bitdely one, with littles bars to show star activity?

**Comment by moul** [comment]
your project, your fancy bling bling :)

**Comment by moul** [comment]
Nice work,

Can you explain how you choose the badge ?

**Comment by balthazar** [comment]
As defined in the [config](https://github.com/SIGSEV/Starveller/blob/master/src/config/index.js#L12), there is (for now) a ranking system that use the count of stars for the past seven days:
- rank 1: less than 2 stars (prevent self-bump to the next rank)
- rank 2: from 2 to 4 stars
- rank 3: from 5 to 14 stars
- rank 4: from 15 to 29 stars
- rank 5: equal or more than 30 stars

We choose to be kinda low-ish for the requirements at first so that a repo that have been trending one day stay at a good rank. We can tweak the variables in the future if we see that's not good.
We will add this explanation somewhere on the site soon!

**Comment by moul** [comment]
Ok, is the badge here the good one: http://starveller.bangular.io/moul/advanced-ssh-config ?

**Comment by balthazar** [comment]
No, it's the default. The correct one should be calculated every day but we are dealing with an issue #22 that prevent it from being refreshed. Once this is fixed and you wait past midnight (UTC+1), this should be good.

**Comment by moul** [comment]
Ok thank you

**Comment by balthazar** [comment]
@moul Your badge is now accurate

**Comment by moul** [comment]
:+1:
